### ISSUE TITLE
Daylight Savings Time, data-minical-initial, and add_timezone_offset

### ISSUE THREAD

**Issue by oniofchaos** [camerond/jquery-minical#11]
If you're currently in Daylight Savings Time, but you're setting `data-minical-initial` to a string date that is not in Daylight Savings Time, the date appears to jump back a day.

For example, with `data-minical-initial="2015-03-04"`, and `add_timezone_offset` being true, <a href="https://github.com/camerond/jquery-minical/blob/master/source/javascripts/jquery.minical.js.coffee#L279">this line</a> ends up returning `Tue Mar 03 2015 23:00:00 GMT-0800 (PST)`, which causes the displayed date to be 2015-03-03.

It seems like the solution would be to call `new Date(millis).getTimezoneOffset()` instead of `new Date().getTimezoneOffset` so that way you're using the offset from the initial date and not from today's date.

**Comment by thomasmeagher** [comment]
That fixed the issue for me. Thanks @oniofchaos

**Comment by camerond** [comment]
Thanks for this! It's in Minical now so I'm closing this (admittedly very old) issue.
